### ISSUE TITLE
a problem about initial-models

### ISSUE THREAD

**Issue by QHLang** [bowang-lab/DES#1]
Hello，i want to train your DESNet. I have installed git lfs. But an error occurred when I downloaded your code. It shows as follows:

`$ git clone https://github.com/bowang-lab/DES.git
Cloning into 'DES'...
remote: Enumerating objects: 28106, done.
remote: Total 28106 (delta 0), reused 0 (delta 0), pack-reused 28106
Receiving objects: 100% (28106/28106), 48.08 MiB | 66.00 KiB/s, done.
Resolving deltas: 100% (19447/19447), done.
Checking connectivity... done.
Downloading initial_models/COCO300RESET_676753.caffemodel (195 MB)
Error downloading object: initial_models/COCO300RESET_676753.caffemodel (2dd9b57): Smudge error: Error downloading initial_models/COCO300RESET_676753.caffemodel (2dd9b575ce836aa865f03baaa1b030a40b4693124637cf7b9075699f18d07667): [2dd9b575ce836aa865f03baaa1b030a40b4693124637cf7b9075699f18d07667] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /media/cqu/D/LQH/desnet/DES/.git/lfs/logs/20191023T111601.240495768.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: initial_models/COCO300RESET_676753.caffemodel: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
`

   The trained models doesn't exist in the folder of ’initial_models‘ , such as 'VOC300TRAINED_4e04e3.caffemodel' , so that i can't train your DESNet. Could you please tell me how i can solve this problem?  Thanks very much!

**Comment by zydou** [comment]
Hi, this work was done with our collaborators and this repo is only an archive repo.
The error occurred because git LFS is not enabled for this repo. You can clone the original code at https://github.com/bairdzhang/des.git to get the `caffemodel`.
